import Head from 'next/head'
import { useDispatch, useSelector } from 'react-redux'
import { decrement, increment } from '../features/counter';


export default function Home() {

  //i want to read this variable fron this reducer
  const {value} = useSelector(state => state.counter)
  const dispatch = useDispatch();//call any action from any reducer

  return (
    <div>
      <Head>
        <title>Raj</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className=' bg-orange-600 min-h-screen flex items-center justify-center'>
          <div className=' w-80 h-40 bg-white rounded-xl flex items-center justify-center '>

            <div className='flex gap-x-6'>

              <button className=' bg-green-700 w-14 rounded-md border-2 border-green-300 text-xl text-green-200'
               onClick={()=>dispatch(increment())}
              >
                  P+
              </button>

                <p>
                  counter{value}
                </p>

              <button className=' bg-green-700 w-14 rounded-md border-2 border-green-300 text-xl text-green-200'
                onClick={()=>dispatch(decrement())}
              >
                  M-
              </button>

            </div>

          </div>
        </section>
      </main>
    </div>
  )
}