import Head from 'next/head'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Raj</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className=' bg-orange-600 min-h-screen flex items-center justify-center'>
          <div className=' w-80 h-40 bg-white rounded-xl flex items-center justify-center '>

            <div className='flex gap-x-6'>

              <button className=' bg-green-700 w-14 rounded-md border-2 border-green-300 text-xl text-green-200'>
                  P+
              </button>

                <p>
                  counter
                </p>

              <button className=' bg-green-700 w-14 rounded-md border-2 border-green-300 text-xl text-green-200'>
                  M-
              </button>

            </div>

          </div>
        </section>
      </main>
    </div>
  )
}