import Head from 'next/head'


export default function Home() {
  return (
    <div>
      <Head>
        <title>sam</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className=' bg-orange-600 min-h-screen'>
          <div className=' w-80 h-40 bg-black'>

          </div>
        </section>
      </main>
    </div>
  )
}